In [1]:
import pandas as pd

from geopy.geocoders import Nominatim
import time

In [2]:
melted = pd.read_excel('iti_melted_PowerBI.xlsx')

In [3]:
melted

       Unnamed: 0      index  Cluster           ciudad  frecuencia
0               0 2023-06-01        0            Irun          6.0
1               1 2023-06-02        0            Irun          7.0
2               2 2023-06-03        0            Irun          8.0
3               3 2023-06-04        0            Irun          7.0
4               4 2023-06-05        0            Irun          9.0
...           ...        ...      ...              ...         ...
15108       15108 2023-07-06        2  Caldas de Reis          NaN
15109       15109 2023-07-07        2  Caldas de Reis          NaN
15110       15110 2023-07-08        2  Caldas de Reis          NaN
15111       15111 2023-07-09        2  Caldas de Reis          NaN
15112       15112 2023-07-10        2  Caldas de Reis          NaN

[15113 rows x 5 columns]

In [4]:

loc = Nominatim(user_agent="GetLoc")
 
# entering the location name
getLoc = loc.geocode("La Mesa, España")
 
# printing address
print(getLoc.address)
 
# printing latitude and longitude
print("Latitude = ", getLoc.latitude)
print("Longitude = ", getLoc.longitude)

La Mesa, Merindad de Sotoscueva, Burgos, Castilla y León, España
Latitude =  43.0246721
Longitude =  -3.6426042

In [5]:
cache = {}
cache2 = {}

In [6]:
def latitude(texto):
    if texto in cache:
        return cache[texto]
    
    try: 
        # ingresar el nombre de la ubicación
        getLoc = loc.geocode(texto)
        if getLoc is not None:
            latitud = getLoc.latitude
            cache[texto] = latitud
            return latitud
        else:
            return None
    except:
        return None

In [7]:
def longitud(texto):
    if texto in cache2:
        return cache2[texto]
    
    try: 
        # ingresar el nombre de la ubicación
        getLoc = loc.geocode(texto)
        if getLoc is not None:
            longitude = getLoc.longitude
            cache2[texto] = longitude
            return longitude
        else:
            return None
    except:
        return None

In [23]:
unique_vals = melted['ciudad'].unique()

print(unique_vals)

['Irun ' 'San Sebastian ' 'Saint Jean Pied de Port ' 'Zarautz '
 'Roncesvalles ' 'Deba ' 'Zubiri ' 'Markina' 'Pamplona ' 'Gernika Lumo '
 'Puente la Reina ' 'Lezama ' 'Estella ' 'Bilbao ' 'Los Arcos '
 'Portugalete ' 'Logroño' 'Castro Urdiales ' 'Najera ' 'Laredo, España'
 'Santo Domingo de La Calzada ' 'Güemes, Cantabria' 'Belorado '
 'Santander ' 'San Juan De Ortega ' 'Santillana del Mar ' 'Burgos '
 'Comillas ' 'Hornillos Del Camino ' 'Colombres ' 'Castrojeriz ' 'Llanes '
 'Fromista ' 'Ribadesella ' 'Carrion De Los Condes ' 'Sebrayo '
 'Terradillos De Los Templarios ' 'Gijon ' 'Bercianos Del Real Camino '
 'Aviles ' 'Oviedo ' 'Mansilla De Las Mulas ' 'Muros de Nalon '
 'Leon, España' 'San Juan de Villapañada' 'Granja de Moreruela '
 'Soto de Luiña ' 'San Martin Del Camino ' 'Salas ' 'Tabara ' 'Cadavedo '
 'Astorga ' 'Tineo ' 'Santa Marta de Tera ' 'Luarca ' 'Foncebadon '
 'Pola de Allande ' 'Mombuey ' 'Ponferrada ' 'La Caridad '
 'La Mesa, España' 'Puebla de Sanabria ' 'Villafranca Del Bierzo '
 'Ribadeo ' 'Grandas de Salime ' 'Lubian ' 'Viana do Castelo '
 'O Cebreiro ' 'Lourenza ' 'A Fonsagrada ' 'A Gudiña ' 'Caminha '
 'Triacastela ' 'Abadin ' 'O Cadavo ' 'Ferrol ' 'Laza ' 'Mougas '
 'Sarria ' 'Vilalba ' 'Lugo ' 'Vigo ' 'Neda ' 'Xunqueira de Ambia '
 'Ramallosa ' 'Portomarin ' 'Baamonde ' 'San Romao da Retorta '
 'Redondela ' 'Ourense ' 'Pontedeume ' 'Palas de Rei '
 'Sobrado dos Monxes ' 'Melide ' 'Pontevedra ' 'Cea ' 'Betanzos ' 'Arzua '
 'Caldas de Reis' 'A Laxe ' 'Bruma, Portugal' 'Santiago de Compostela'
 'Lisboa' 'Alhandra, Portugal' 'Azambuja ' 'Santarem ' 'Golega ' 'Tomar '
 'Alvaiazere ' 'Rabacal ' 'Coimbra ' 'Mealhada ' 'Agueda '
 'Albergaria A Velha ' 'Oliveira de Azemeis ' 'Oporto ' 'Grijo '
 'Labruge ' 'Povoa de Varzim ' 'Vilarinho ' 'Marinhas ' 'Barcelos '
 'Ponte de Lima ' 'Rubiaes ' 'Tui ' 'O Porriño' 'Caldas de Reis ']

In [24]:
for ele in unique_vals:
    inicio = time.time()
    latitude(ele)
    longitud(ele)
    print(ele)
    fin = time.time()
    print(fin-inicio)

Irun
3.0994415283203125e-05
San Sebastian
5.0067901611328125e-06
Saint Jean Pied de Port
4.0531158447265625e-06
Zarautz
4.291534423828125e-06
Roncesvalles
3.814697265625e-06
Deba
3.814697265625e-06
Zubiri
4.0531158447265625e-06
Markina
4.0531158447265625e-06
Pamplona
4.291534423828125e-06
Gernika Lumo
4.0531158447265625e-06
Puente la Reina
3.814697265625e-06
Lezama
3.814697265625e-06
Estella
4.0531158447265625e-06
Bilbao
4.0531158447265625e-06
Los Arcos
4.0531158447265625e-06
Portugalete
4.0531158447265625e-06
Logroño
4.0531158447265625e-06
Castro Urdiales
4.0531158447265625e-06
Najera
5.245208740234375e-06
Laredo, España
3.814697265625e-06
Santo Domingo de La Calzada
3.814697265625e-06
Güemes, Cantabria
0.6428630352020264
Belorado
1.5020370483398438e-05
Santander
9.775161743164062e-06
San Juan De Ortega
8.821487426757812e-06
Santillana del Mar
9.059906005859375e-06
Burgos
9.059906005859375e-06
Comillas
1.0013580322265625e-05
Hornillos Del Camino
8.106231689453125e-06
Colombres
1.9788742065429688e-05
Castrojeriz
7.867813110351562e-06
Llanes
2.09808349609375e-05
Fromista
1.0013580322265625e-05
Ribadesella
9.059906005859375e-06
Carrion De Los Condes
2.6702880859375e-05
Sebrayo
2.6941299438476562e-05
Terradillos De Los Templarios
9.059906005859375e-06
Gijon
9.059906005859375e-06
Bercianos Del Real Camino
9.298324584960938e-06
Aviles
1.7881393432617188e-05
Oviedo
1.3113021850585938e-05
Mansilla De Las Mulas
9.059906005859375e-06
Muros de Nalon
1.0967254638671875e-05
Leon, España
9.059906005859375e-06
San Juan de Villapañada
1.023603916168213
Granja de Moreruela
1.5974044799804688e-05
Soto de Luiña
1.0251998901367188e-05
San Martin Del Camino
9.775161743164062e-06
Salas
8.821487426757812e-06
Tabara
1.7881393432617188e-05
Cadavedo
4.00543212890625e-05
Astorga
5.2928924560546875e-05
Tineo
1.0967254638671875e-05
Santa Marta de Tera
9.298324584960938e-06
Luarca
1.0967254638671875e-05
Foncebadon
7.867813110351562e-06
Pola de Allande
9.059906005859375e-06
Mombuey
1.71661376953125e-05
Ponferrada
8.106231689453125e-06
La Caridad
8.106231689453125e-06
La Mesa, España
1.0251998901367188e-05
Puebla de Sanabria
1.811981201171875e-05
Villafranca Del Bierzo
8.106231689453125e-06
Ribadeo
2.3126602172851562e-05
Grandas de Salime
1.0013580322265625e-05
Lubian
8.821487426757812e-06
Viana do Castelo
1.7881393432617188e-05
O Cebreiro
9.059906005859375e-06
Lourenza
2.09808349609375e-05
A Fonsagrada
1.5974044799804688e-05
A Gudiña
1.7881393432617188e-05
Caminha
1.1205673217773438e-05
Triacastela
8.821487426757812e-06
Abadin
8.106231689453125e-06
O Cadavo
8.344650268554688e-06
Ferrol
8.821487426757812e-06
Laza
1.0013580322265625e-05
Mougas
8.821487426757812e-06
Sarria
9.059906005859375e-06
Vilalba
8.821487426757812e-06
Lugo
9.059906005859375e-06
Vigo
1.7881393432617188e-05
Neda
1.1920928955078125e-05
Xunqueira de Ambia
7.867813110351562e-06
Ramallosa
9.059906005859375e-06
Portomarin
2.8848648071289062e-05
Baamonde
1.8835067749023438e-05
San Romao da Retorta
1.8835067749023438e-05
Redondela
1.6927719116210938e-05
Ourense
8.821487426757812e-06
Pontedeume
1.71661376953125e-05
Palas de Rei
9.059906005859375e-06
Sobrado dos Monxes
7.867813110351562e-06
Melide
8.821487426757812e-06
Pontevedra
8.821487426757812e-06
Cea
7.867813110351562e-06
Betanzos
1.0013580322265625e-05
Arzua
8.106231689453125e-06
Caldas de Reis
9.059906005859375e-06
A Laxe
8.106231689453125e-06
Bruma, Portugal
9.059906005859375e-06
Santiago de Compostela
9.298324584960938e-06
Lisboa
1.2159347534179688e-05
Alhandra, Portugal
9.059906005859375e-06
Azambuja
8.106231689453125e-06
Santarem
7.867813110351562e-06
Golega
1.7881393432617188e-05
Tomar
9.059906005859375e-06
Alvaiazere
1.6927719116210938e-05
Rabacal
8.106231689453125e-06
Coimbra
1.0013580322265625e-05
Mealhada
1.6927719116210938e-05
Agueda
1.71661376953125e-05
Albergaria A Velha
7.867813110351562e-06
Oliveira de Azemeis
1.0013580322265625e-05
Oporto
8.821487426757812e-06
Grijo
1.6927719116210938e-05
Labruge
1.6927719116210938e-05
Povoa de Varzim
2.6702880859375e-05
Vilarinho
8.106231689453125e-06
Marinhas
1.3113021850585938e-05
Barcelos
1.0967254638671875e-05
Ponte de Lima
1.6927719116210938e-05
Rubiaes
1.8835067749023438e-05
Tui
8.106231689453125e-06
O Porriño
0.918389081954956
Caldas de Reis
1.3113021850585938e-05

In [25]:
def add_coords_to_dataframe(df, lat_dict, long_dict):
    df['Latitud'] = df['ciudad'].map(lat_dict)
    df['Longitud'] = df['ciudad'].map(long_dict)
    return df

In [26]:
cache

{'Irun ': 43.3383176,
 'San Sebastian ': 43.3224219,
 'Saint Jean Pied de Port ': 43.1629528,
 'Zarautz ': 43.2834873,
 'Roncesvalles ': 4.10391495,
 'Deba ': 43.294141,
 'Zubiri ': 42.9305828,
 'Markina': 42.98026485,
 'Pamplona ': 42.8182536,
 'Gernika Lumo ': 43.3143628,
 'Puente la Reina ': 42.6717107,
 'Lezama ': 43.2743248,
 'Estella ': 42.672094,
 'Bilbao ': 43.2630018,
 'Los Arcos ': 42.5697418,
 'Portugalete ': 43.3191292,
 'Logroño': 42.4661196,
 'Castro Urdiales ': 43.3843347,
 'Najera ': 42.416745,
 'Laredo, España': 43.41063,
 'Santo Domingo de La Calzada ': 42.4406711,
 'Belorado ': 42.4197032,
 'Santander ': 43.4620412,
 'San Juan De Ortega ': 42.3752668,
 'Santillana del Mar ': 43.3906511,
 'Burgos ': 42.343926,
 'Comillas ': 43.3855344,
 'Hornillos Del Camino ': 42.3385369,
 'Colombres ': 43.3749259,
 'Castrojeriz ': 42.2883697,
 'Llanes ': 43.4211205,
 'Fromista ': 42.2676867,
 'Ribadesella ': 43.4617129,
 'Carrion De Los Condes ': 42.3385404,
 'Sebrayo ': 43.4994298,
 'Terradillos De Los Templarios ': 42.3629914,
 'Gijon ': 43.5449422,
 'Bercianos Del Real Camino ': 42.3876814,
 'Aviles ': 43.5554436,
 'Oviedo ': 43.3604218,
 'Mansilla De Las Mulas ': 42.4991013,
 'Muros de Nalon ': 43.5429817,
 'Leon, España': 42.63414505,
 'Granja de Moreruela ': 41.809162,
 'Soto de Luiña ': 43.5620451,
 'San Martin Del Camino ': 42.4951315,
 'Salas ': 43.4079447,
 'Tabara ': 41.8248097,
 'Cadavedo ': 43.36624,
 'Astorga ': 42.4553555,
 'Tineo ': 43.333974,
 'Santa Marta de Tera ': 41.9949286,
 'Luarca ': 43.5439003,
 'Foncebadon ': 42.4914071,
 'Pola de Allande ': 43.271901,
 'Mombuey ': 42.0226242,
 'Ponferrada ': 42.5454124,
 'La Caridad ': 21.3711261,
 'La Mesa, España': 43.0246721,
 'Puebla de Sanabria ': 42.054621,
 'Villafranca Del Bierzo ': 42.605583,
 'Ribadeo ': 43.5361589,
 'Grandas de Salime ': 43.2176587,
 'Lubian ': 42.0352659,
 'Viana do Castelo ': 41.8803257,
 'O Cebreiro ': 42.7188437,
 'Lourenza ': 43.459566,
 'A Fonsagrada ': 43.1248311,
 'A Gudiña ': 42.0605483,
 'Caminha ': 41.8757598,
 'Triacastela ': 42.7563403,
 'Abadin ': 57.1482429,
 'O Cadavo ': 43.0151911,
 'Ferrol ': 43.4846862,
 'Laza ': 42.0604757,
 'Mougas ': 42.0660216,
 'Sarria ': 42.7784203,
 'Vilalba ': 43.2965293,
 'Lugo ': 43.0462247,
 'Vigo ': 42.2376602,
 'Neda ': 43.5002779,
 'Xunqueira de Ambia ': 42.2050642,
 'Ramallosa ': 42.1219443,
 'Portomarin ': 42.808161,
 'Baamonde ': 43.1741924,
 'San Romao da Retorta ': 42.9637515,
 'Redondela ': 42.284221,
 'Ourense ': 42.1968459,
 'Pontedeume ': 43.4072585,
 'Palas de Rei ': 42.8739125,
 'Sobrado dos Monxes ': 43.0404996,
 'Melide ': 42.9145741,
 'Pontevedra ': 42.6075172,
 'Cea ': 42.4619773,
 'Betanzos ': 43.2729197,
 'Arzua ': 42.9279921,
 'Caldas de Reis': 42.6041056,
 'A Laxe ': 42.7882476,
 'Bruma, Portugal': 41.3748746,
 'Santiago de Compostela': 42.8804219,
 'Lisboa': 38.7077507,
 'Alhandra, Portugal': 38.9233146,
 'Azambuja ': 39.0689884,
 'Santarem ': 39.2363637,
 'Golega ': 39.4017959,
 'Tomar ': 39.6036596,
 'Alvaiazere ': 39.816133300000004,
 'Rabacal ': 40.8545347,
 'Coimbra ': 40.2111931,
 'Mealhada ': 40.3792003,
 'Agueda ': 40.5785006,
 'Albergaria A Velha ': 40.6906888,
 'Oliveira de Azemeis ': 40.8390118,
 'Oporto ': 41.1494512,
 'Grijo ': 41.5027019,
 'Labruge ': 41.2779415,
 'Povoa de Varzim ': 41.3794188,
 'Vilarinho ': 41.7076589,
 'Marinhas ': 41.8786123,
 'Barcelos ': 41.5314496,
 'Ponte de Lima ': 41.7675021,
 'Rubiaes ': 41.8977757,
 'Tui ': 42.0501375,
 'Caldas de Reis ': 42.6041056,
 'Güemes, Cantabria': 43.45581,
 'San Juan de Villapañada': 43.3919429,
 'O Porriño': 42.1618812}

In [27]:
melted = add_coords_to_dataframe(melted, cache, cache2)

In [28]:
melted[melted['Latitud'].isna()].ciudad.unique()

array([], dtype=object)

In [19]:
getLoc = loc.geocode("Güemes, Cantabria")
 
# printing address
print(getLoc.address)
 
# printing latitude and longitude
print("Latitude = ", getLoc.latitude)
print("Longitude = ", getLoc.longitude)

Güemes, Bareyo, Trasmiera, Cantabria, 39191, España
Latitude =  43.45581
Longitude =  -3.63481

In [20]:
melted['ciudad'] = [s.replace("Guemes, Portugal" , "Güemes, Cantabria") for s in melted.ciudad]
melted['ciudad'] = [s.replace("San Juan de VillapaÃ±ada " , "San Juan de Villapañada") for s in melted.ciudad]

melted['ciudad'] = [s.replace("O PorriÃ±o " , "O Porriño") for s in melted.ciudad]

In [29]:
melted.columns

Index(['Unnamed: 0', 'index', 'Cluster', 'ciudad', 'frecuencia', 'Latitud',
       'Longitud'],
      dtype='object')

In [30]:
melted = melted[[ 'index', 'Cluster', 'ciudad', 'frecuencia', 'Latitud',
       'Longitud']]

In [31]:
melted

           index  Cluster           ciudad  frecuencia    Latitud  Longitud
0     2023-06-01        0            Irun          6.0  43.338318 -1.788809
1     2023-06-02        0            Irun          7.0  43.338318 -1.788809
2     2023-06-03        0            Irun          8.0  43.338318 -1.788809
3     2023-06-04        0            Irun          7.0  43.338318 -1.788809
4     2023-06-05        0            Irun          9.0  43.338318 -1.788809
...          ...      ...              ...         ...        ...       ...
15108 2023-07-06        2  Caldas de Reis          NaN  42.604106 -8.642171
15109 2023-07-07        2  Caldas de Reis          NaN  42.604106 -8.642171
15110 2023-07-08        2  Caldas de Reis          NaN  42.604106 -8.642171
15111 2023-07-09        2  Caldas de Reis          NaN  42.604106 -8.642171
15112 2023-07-10        2  Caldas de Reis          NaN  42.604106 -8.642171

[15113 rows x 6 columns]

In [ ]:
melted.to_excel('melted_con_long.xlsx')

In [2]:
melted = pd.read_excel('melted_con_long.xlsx')

In [5]:
len(melted.ciudad.unique())

127

In [6]:
clust = pd.read_csv('Treated_csv/entries_with_labels_fin.csv')
clust = clust.set_index('Fecha')
clust.index = pd.to_datetime(clust.index)

In [7]:
clust_pred = clust[(clust.Mes == 7) & (clust.Dia < 12) & (clust.Año == 2022)]

In [8]:
clust_pred.columns

Index(['Sexo', 'Edad', 'Continente', 'Pais', 'Autonomia', 'Medio', 'Motivo',
       'Camino', 'Origen', 'Profesion', 'Latitud', 'Longitud', 'Año', 'Mes',
       'Dia', 'Dialv', 'Cluster'],
      dtype='object')

In [9]:
clust_pred =clust_pred[['Cluster','Origen','Camino','Latitud', 'Longitud' ]]

In [10]:
clust_pred

,Cluster,Origen,Camino,Latitud,Longitud
Fecha,,,,,
2022-07-01 10:08:59,1.0,Oporto Costa,Costa Camino Portugues,41.163505,-8.527522
2022-07-01 10:09:02,1.0,Oporto Costa,Costa Camino Portugues,41.163505,-8.527522
2022-07-01 10:09:04,1.0,Oporto Costa,Costa Camino Portugues,41.163505,-8.527522
2022-07-01 10:09:06,1.0,Oporto Costa,Costa Camino Portugues,41.163505,-8.527522
2022-07-01 10:20:35,2.0,Sarria,Frances-Camino de,42.778420,-7.414661
...,...,...,...,...,...
2022-07-11 19:01:39,1.0,Bayonne,Norte-Camino de,43.494514,-1.473666
2022-07-11 19:01:43,1.0,Bayonne,Norte-Camino de,43.494514,-1.473666
2022-07-11 19:03:07,1.0,Baiona,Costa Camino Portugues,43.494514,-1.473666
2022-07-11 19:04:23,1.0,Baiona,Costa Camino Portugues,43.494514,-1.473666
2022-07-11 19:04:43,1.0,Baiona,Costa Camino Portugues,43.494514,-1.473666

In [11]:
etaps = pd.read_excel('Caminos con etapas 2.xlsx', header= 2)
etaps = etaps.rename(columns={'Ciudad': 'Origen'})


etaps.head(2)

    Camino  Etapa                  Origen    km
0  Frances      0  Santiago de Compostela   0.0
1  Frances      1             O Pedrouzo   19.4

In [12]:
def limpiar_columna(df, columna):
    df[columna] = df[columna].apply(lambda x: x.rstrip())
    return df

In [13]:
limpiar_columna(etaps,'Origen')

       Camino  Etapa                  Origen    km
0     Frances      0  Santiago de Compostela   0.0
1     Frances      1              O Pedrouzo  19.4
2     Frances      2                   Arzúa  19.3
3     Frances      3            Palas de Rei  28.5
4     Frances      4              Portomarín  24.8
..        ...    ...                     ...   ...
140  Sanabrés      9      Puebla de Sanabria  29.5
141  Sanabrés     10                 Mombuey  31.7
142  Sanabrés     11     Santa Marta de Tera  36.1
143  Sanabrés     12                  Tábara  22.7
144  Sanabrés     13     Granja de Moreruela  25.3

[145 rows x 4 columns]

In [14]:
etaps.Camino.unique()

array(['Frances', 'Ingles', 'Norte', 'Portugues',
       'Portugués por la costa', 'Primitivo', 'Sanabrés'], dtype=object)

In [15]:
etaps['Origen'] = [s.replace("O Cebreiro" , "Cebreiro") for s in etaps.Origen]  
etaps['Origen'] = [s.replace("S. Jean Pied Port" , "S. Jean P. Port") for s in etaps.Origen]  
etaps['Origen'] = [s.replace("Tui" , "Valença do Minho") for s in etaps.Origen]  
etaps['Camino'] = [s.replace("Portugués por la costa" , "Costa") for s in etaps.Camino]

In [16]:
clust_pred['Camino'] = [s.replace("Costa Camino Portugues" , "Costa") for s in clust_pred.Camino]  
clust_pred['Camino'] = [s.replace("Frances-Camino de" , "Frances") for s in clust_pred.Camino]  

clust_pred['Camino'] = [s.replace("Portugues-Camino" , "Portugues") for s in clust_pred.Camino]  

clust_pred['Camino'] = [s.replace("Ingles-Camino" , "Ingles") for s in clust_pred.Camino]  
clust_pred['Camino'] = [s.replace("Ingles-Camino" , "Ingles") for s in clust_pred.Camino]  

clust_pred['Camino'] = [s.replace("Primitivo-Camino" , "Primitivo") for s in clust_pred.Camino]  

clust_pred['Camino'] = [s.replace("Norte-Camino de" , "Norte") for s in clust_pred.Camino]

In [17]:
clust_pred.Camino.unique()

array(['Costa', 'Frances', 'Portugues', 'Primitivo', 'Otros caminos',
       'Norte', 'Ingles', 'Via de la Plata', 'San Salvador',
       'Muxia-Finisterre', 'Invierno de Camino', 'Miñoto Ribeiro',
       'Camino del Mar', 'Muros - Noia Camino', 'Geira e Arrieiros',
       'Camino olvidado'], dtype=object)

In [18]:
clust_pred['OrigenCamino'] = clust_pred['Origen'] + clust_pred['Camino']

In [19]:
etaps['OrigenCamino'] = etaps['Origen'] + etaps['Camino']

In [20]:
etap_dict = dict(zip(etaps['OrigenCamino'], etaps['Camino']))
etap_dict

{'Santiago de CompostelaFrances': 'Frances',
 'O PedrouzoFrances': 'Frances',
 'ArzúaFrances': 'Frances',
 'Palas de ReiFrances': 'Frances',
 'PortomarínFrances': 'Frances',
 'SarriaFrances': 'Frances',
 'TriacastelaFrances': 'Frances',
 'CebreiroFrances': 'Frances',
 'Villafranca Del BierzoFrances': 'Frances',
 'PonferradaFrances': 'Frances',
 'FoncebadónFrances': 'Frances',
 'AstorgaFrances': 'Frances',
 'San Martín Del CaminoFrances': 'Frances',
 'LeónFrances': 'Frances',
 'Mansilla De Las MulasFrances': 'Frances',
 'Bercianos Del Real CaminoFrances': 'Frances',
 'Terradillos De Los TemplariosFrances': 'Frances',
 'Carrión De Los CondesFrances': 'Frances',
 'FrómistaFrances': 'Frances',
 'CastrojerizFrances': 'Frances',
 'Hornillos Del CaminoFrances': 'Frances',
 'BurgosFrances': 'Frances',
 'San Juan De OrtegaFrances': 'Frances',
 'BeloradoFrances': 'Frances',
 'Santo Domingo de La CalzadaFrances': 'Frances',
 'NájeraFrances': 'Frances',
 'LogroñoFrances': 'Frances',
 'Los ArcosFrances': 'Frances',
 'EstellaFrances': 'Frances',
 'Puente la ReinaFrances': 'Frances',
 'PamplonaFrances': 'Frances',
 'ZubiriFrances': 'Frances',
 'RoncesvallesFrances': 'Frances',
 'Saint Jean Pied de PortFrances': 'Frances',
 'Santiago de CompostelaIngles': 'Ingles',
 'SigüeiroIngles': 'Ingles',
 'BrumaIngles': 'Ingles',
 'BetanzosIngles': 'Ingles',
 'PontedeumeIngles': 'Ingles',
 'NedaIngles': 'Ingles',
 'FerrolIngles': 'Ingles',
 'Santiago de CompostelaNorte': 'Norte',
 'O PedrouzoNorte': 'Norte',
 'ArzúaNorte': 'Norte',
 'Sobrado dos MonxesNorte': 'Norte',
 'BaamondeNorte': 'Norte',
 'VilalbaNorte': 'Norte',
 'AbadínNorte': 'Norte',
 'LourenzáNorte': 'Norte',
 'RibadeoNorte': 'Norte',
 'La CaridadNorte': 'Norte',
 'LuarcaNorte': 'Norte',
 'CadavedoNorte': 'Norte',
 'Soto de LuiñaNorte': 'Norte',
 'Muros de NalónNorte': 'Norte',
 'AvilésNorte': 'Norte',
 'GijónNorte': 'Norte',
 'SebrayoNorte': 'Norte',
 'RibadesellaNorte': 'Norte',
 'LlanesNorte': 'Norte',
 'ColombresNorte': 'Norte',
 'ComillasNorte': 'Norte',
 'Santillana del MarNorte': 'Norte',
 'SantanderNorte': 'Norte',
 'GüemesNorte': 'Norte',
 'LaredoNorte': 'Norte',
 'Castro UrdialesNorte': 'Norte',
 'PortugaleteNorte': 'Norte',
 'BilbaoNorte': 'Norte',
 'LezamaNorte': 'Norte',
 'Gernika LumoNorte': 'Norte',
 'MarkinaNorte': 'Norte',
 'DebaNorte': 'Norte',
 'ZarautzNorte': 'Norte',
 'San SebastiánNorte': 'Norte',
 'IrúnNorte': 'Norte',
 'Santiago de CompostelaPortugues': 'Portugues',
 'PadrónPortugues': 'Portugues',
 'Caldas de ReisPortugues': 'Portugues',
 'PontevedraPortugues': 'Portugues',
 'RedondelaPortugues': 'Portugues',
 'O PorriñoPortugues': 'Portugues',
 'Valença do MinhoPortugues': 'Portugues',
 'RubiãesPortugues': 'Portugues',
 'Ponte de LimaPortugues': 'Portugues',
 'BarcelosPortugues': 'Portugues',
 'VilarinhoPortugues': 'Portugues',
 'OportoPortugues': 'Portugues',
 'GrijóPortugues': 'Portugues',
 'Oliveira de AzeméisPortugues': 'Portugues',
 'Albergaria A VelhaPortugues': 'Portugues',
 'ÁguedaPortugues': 'Portugues',
 'MealhadaPortugues': 'Portugues',
 'CoímbraPortugues': 'Portugues',
 'RabaçalPortugues': 'Portugues',
 'AlvaiázerePortugues': 'Portugues',
 'TomarPortugues': 'Portugues',
 'GolegãPortugues': 'Portugues',
 'SantarémPortugues': 'Portugues',
 'AzambujaPortugues': 'Portugues',
 'AlhandraPortugues': 'Portugues',
 'LisboaPortugues': 'Portugues',
 'Santiago de CompostelaCosta': 'Costa',
 'PadrónCosta': 'Costa',
 'Caldas de ReisCosta': 'Costa',
 'PontevedraCosta': 'Costa',
 'RedondelaCosta': 'Costa',
 'VigoCosta': 'Costa',
 'RamallosaCosta': 'Costa',
 'MougásCosta': 'Costa',
 'CaminhaCosta': 'Costa',
 'Viana do CasteloCosta': 'Costa',
 'MarinhasCosta': 'Costa',
 'Póvoa de VarzimCosta': 'Costa',
 'LabrugeCosta': 'Costa',
 'OportoCosta': 'Costa',
 'Santiago de CompostelaPrimitivo': 'Primitivo',
 'O PedrouzoPrimitivo': 'Primitivo',
 'ArzúaPrimitivo': 'Primitivo',
 'MelidePrimitivo': 'Primitivo',
 'San Romao da RetortaPrimitivo': 'Primitivo',
 'LugoPrimitivo': 'Primitivo',
 'O CádavoPrimitivo': 'Primitivo',
 'A FonsagradaPrimitivo': 'Primitivo',
 'Grandas de SalimePrimitivo': 'Primitivo',
 'La MesaPrimitivo': 'Primitivo',
 'Pola de AllandePrimitivo': 'Primitivo',
 'TineoPrimitivo': 'Primitivo',
 'SalasPrimitivo': 'Primitivo',
 'San Juan de VillapañadaPrimitivo': 'Primitivo',
 'OviedoPrimitivo': 'Primitivo',
 'Santiago de CompostelaSanabrés': 'Sanabrés',
 'OuteiroSanabrés': 'Sanabrés',
 'A LaxeSanabrés': 'Sanabrés',
 'CeaSanabrés': 'Sanabrés',
 'OurenseSanabrés': 'Sanabrés',
 'Xunqueira de AmbíaSanabrés': 'Sanabrés',
 'LazaSanabrés': 'Sanabrés',
 'A GudiñaSanabrés': 'Sanabrés',
 'LubiánSanabrés': 'Sanabrés',
 'Puebla de SanabriaSanabrés': 'Sanabrés',
 'MombueySanabrés': 'Sanabrés',
 'Santa Marta de TeraSanabrés': 'Sanabrés',
 'TábaraSanabrés': 'Sanabrés',
 'Granja de MoreruelaSanabrés': 'Sanabrés'}

In [21]:
clust_pred['Camino'] = clust_pred['OrigenCamino'].map(etap_dict)

clust_pred[clust_pred.Camino.isna()].Origen.value_counts()

Tui                2036
S. Jean P. Port    1373
Ourense             374
Porriño             371
Oporto Costa        370
                   ...
Luxemburgo            1
Villademoros          1
Compostilla           1
Columbrianos          1
Berducedo             1
Name: Origen, Length: 192, dtype: int64

In [22]:
clust_pred.loc[clust_pred['Origen'] == 'Tui', 'Camino'] = 'Portugues'
clust_pred.loc[clust_pred['Origen'] == 'S. Jean P. Port', 'Camino'] = 'Frances'
clust_pred.loc[clust_pred['Origen'] == 'Sarria', 'Camino'] = 'Frances'

In [23]:
clust_pred[clust_pred.Camino.isna()].Origen.value_counts()

Ourense         374
Porriño         371
Oporto Costa    370
Madrid          370
Baiona          328
               ...
Borres            1
Orisson           1
Compostilla       1
Lédigos           1
Berducedo         1
Name: Origen, Length: 189, dtype: int64

In [24]:
etap_dict2 = dict(zip(etaps['OrigenCamino'], etaps['Etapa']))
etap_dict2

{'Santiago de CompostelaFrances': 0,
 'O PedrouzoFrances': 1,
 'ArzúaFrances': 2,
 'Palas de ReiFrances': 3,
 'PortomarínFrances': 4,
 'SarriaFrances': 5,
 'TriacastelaFrances': 6,
 'CebreiroFrances': 7,
 'Villafranca Del BierzoFrances': 8,
 'PonferradaFrances': 9,
 'FoncebadónFrances': 10,
 'AstorgaFrances': 11,
 'San Martín Del CaminoFrances': 12,
 'LeónFrances': 13,
 'Mansilla De Las MulasFrances': 14,
 'Bercianos Del Real CaminoFrances': 15,
 'Terradillos De Los TemplariosFrances': 16,
 'Carrión De Los CondesFrances': 17,
 'FrómistaFrances': 18,
 'CastrojerizFrances': 19,
 'Hornillos Del CaminoFrances': 20,
 'BurgosFrances': 21,
 'San Juan De OrtegaFrances': 22,
 'BeloradoFrances': 23,
 'Santo Domingo de La CalzadaFrances': 24,
 'NájeraFrances': 25,
 'LogroñoFrances': 26,
 'Los ArcosFrances': 27,
 'EstellaFrances': 28,
 'Puente la ReinaFrances': 29,
 'PamplonaFrances': 30,
 'ZubiriFrances': 31,
 'RoncesvallesFrances': 32,
 'Saint Jean Pied de PortFrances': 33,
 'Santiago de CompostelaIngles': 0,
 'SigüeiroIngles': 1,
 'BrumaIngles': 2,
 'BetanzosIngles': 3,
 'PontedeumeIngles': 4,
 'NedaIngles': 5,
 'FerrolIngles': 6,
 'Santiago de CompostelaNorte': 0,
 'O PedrouzoNorte': 1,
 'ArzúaNorte': 2,
 'Sobrado dos MonxesNorte': 3,
 'BaamondeNorte': 4,
 'VilalbaNorte': 5,
 'AbadínNorte': 6,
 'LourenzáNorte': 7,
 'RibadeoNorte': 8,
 'La CaridadNorte': 9,
 'LuarcaNorte': 10,
 'CadavedoNorte': 11,
 'Soto de LuiñaNorte': 12,
 'Muros de NalónNorte': 13,
 'AvilésNorte': 14,
 'GijónNorte': 15,
 'SebrayoNorte': 16,
 'RibadesellaNorte': 17,
 'LlanesNorte': 18,
 'ColombresNorte': 19,
 'ComillasNorte': 20,
 'Santillana del MarNorte': 21,
 'SantanderNorte': 22,
 'GüemesNorte': 23,
 'LaredoNorte': 24,
 'Castro UrdialesNorte': 25,
 'PortugaleteNorte': 26,
 'BilbaoNorte': 27,
 'LezamaNorte': 28,
 'Gernika LumoNorte': 29,
 'MarkinaNorte': 30,
 'DebaNorte': 31,
 'ZarautzNorte': 32,
 'San SebastiánNorte': 33,
 'IrúnNorte': 34,
 'Santiago de CompostelaPortugues': 0,
 'PadrónPortugues': 1,
 'Caldas de ReisPortugues': 2,
 'PontevedraPortugues': 3,
 'RedondelaPortugues': 4,
 'O PorriñoPortugues': 5,
 'Valença do MinhoPortugues': 6,
 'RubiãesPortugues': 7,
 'Ponte de LimaPortugues': 8,
 'BarcelosPortugues': 9,
 'VilarinhoPortugues': 10,
 'OportoPortugues': 11,
 'GrijóPortugues': 12,
 'Oliveira de AzeméisPortugues': 13,
 'Albergaria A VelhaPortugues': 14,
 'ÁguedaPortugues': 15,
 'MealhadaPortugues': 16,
 'CoímbraPortugues': 17,
 'RabaçalPortugues': 18,
 'AlvaiázerePortugues': 19,
 'TomarPortugues': 20,
 'GolegãPortugues': 21,
 'SantarémPortugues': 22,
 'AzambujaPortugues': 23,
 'AlhandraPortugues': 24,
 'LisboaPortugues': 25,
 'Santiago de CompostelaCosta': 0,
 'PadrónCosta': 1,
 'Caldas de ReisCosta': 2,
 'PontevedraCosta': 3,
 'RedondelaCosta': 4,
 'VigoCosta': 5,
 'RamallosaCosta': 6,
 'MougásCosta': 7,
 'CaminhaCosta': 8,
 'Viana do CasteloCosta': 9,
 'MarinhasCosta': 10,
 'Póvoa de VarzimCosta': 11,
 'LabrugeCosta': 12,
 'OportoCosta': 13,
 'Santiago de CompostelaPrimitivo': 0,
 'O PedrouzoPrimitivo': 1,
 'ArzúaPrimitivo': 2,
 'MelidePrimitivo': 3,
 'San Romao da RetortaPrimitivo': 4,
 'LugoPrimitivo': 5,
 'O CádavoPrimitivo': 6,
 'A FonsagradaPrimitivo': 7,
 'Grandas de SalimePrimitivo': 8,
 'La MesaPrimitivo': 9,
 'Pola de AllandePrimitivo': 10,
 'TineoPrimitivo': 11,
 'SalasPrimitivo': 12,
 'San Juan de VillapañadaPrimitivo': 13,
 'OviedoPrimitivo': 14,
 'Santiago de CompostelaSanabrés': 0,
 'OuteiroSanabrés': 1,
 'A LaxeSanabrés': 2,
 'CeaSanabrés': 3,
 'OurenseSanabrés': 4,
 'Xunqueira de AmbíaSanabrés': 5,
 'LazaSanabrés': 6,
 'A GudiñaSanabrés': 7,
 'LubiánSanabrés': 8,
 'Puebla de SanabriaSanabrés': 9,
 'MombueySanabrés': 10,
 'Santa Marta de TeraSanabrés': 11,
 'TábaraSanabrés': 12,
 'Granja de MoreruelaSanabrés': 13}

In [25]:
clust_pred['Etapa'] = clust_pred['OrigenCamino'].map(etap_dict2)

In [26]:
clust_pred[clust_pred.Etapa.isna()].Origen.value_counts()

Tui                2036
S. Jean P. Port    1373
Ourense             374
Porriño             371
Oporto Costa        370
                   ...
Luxemburgo            1
Villademoros          1
Compostilla           1
Columbrianos          1
Berducedo             1
Name: Origen, Length: 192, dtype: int64

In [27]:
clust_pred.loc[clust_pred['Origen'] == 'Tui', 'Etapa'] = 6
clust_pred.loc[clust_pred['Origen'] == 'S. Jean P. Port', 'Etapa'] = 33

In [28]:
etaps[etaps.Origen == "Bayonne"]

Empty DataFrame
Columns: [Camino, Etapa, Origen, km, OrigenCamino]
Index: []

In [29]:
etaps[etaps.Camino == "Frances"]

,Camino,Etapa,Origen,km,OrigenCamino
0,Frances,0,Santiago de Compostela,0.0,Santiago de CompostelaFrances
1,Frances,1,O Pedrouzo,19.4,O PedrouzoFrances
2,Frances,2,Arzúa,19.3,ArzúaFrances
3,Frances,3,Palas de Rei,28.5,Palas de ReiFrances
4,Frances,4,Portomarín,24.8,PortomarínFrances
5,Frances,5,Sarria,22.2,SarriaFrances
6,Frances,6,Triacastela,17.8,TriacastelaFrances
7,Frances,7,Cebreiro,20.8,CebreiroFrances
8,Frances,8,Villafranca Del Bierzo,27.8,Villafranca Del BierzoFrances
9,Frances,9,Ponferrada,24.2,PonferradaFrances
10,Frances,10,Foncebadón,26.8,FoncebadónFrances
11,Frances,11,Astorga,25.8,AstorgaFrances
12,Frances,12,San Martín Del Camino,23.7,San Martín Del CaminoFrances
13,Frances,13,León,24.6,LeónFrances
14,Frances,14,Mansilla De Las Mulas,18.5,Mansilla De Las MulasFrances
15,Frances,15,Bercianos Del Real Camino,26.3,Bercianos Del Real CaminoFrances
16,Frances,16,Terradillos De Los Templarios,23.2,Terradillos De Los TemplariosFrances
17,Frances,17,Carrión De Los Condes,26.3,Carrión De Los CondesFrances
18,Frances,18,Frómista,18.8,FrómistaFrances
19,Frances,19,Castrojeriz,24.7,CastrojerizFrances
20,Frances,20,Hornillos Del Camino,19.9,Hornillos Del CaminoFrances
21,Frances,21,Burgos,21.0,BurgosFrances
22,Frances,22,San Juan De Ortega,25.8,San Juan De OrtegaFrances
23,Frances,23,Belorado,23.9,BeloradoFrances
24,Frances,24,Santo Domingo de La Calzada,22.0,Santo Domingo de La CalzadaFrances
25,Frances,25,Nájera,20.7,NájeraFrances
26,Frances,26,Logroño,29.0,LogroñoFrances
27,Frances,27,Los Arcos,27.6,Los ArcosFrances
28,Frances,28,Estella,21.3,EstellaFrances
29,Frances,29,Puente la Reina,21.6,Puente la ReinaFrances
30,Frances,30,Pamplona,23.9,PamplonaFrances
31,Frances,31,Zubiri,20.4,ZubiriFrances
32,Frances,32,Roncesvalles,21.4,RoncesvallesFrances
33,Frances,33,Saint Jean Pied de Port,24.2,Saint Jean Pied de PortFrances

In [30]:
clust_pred.loc[clust_pred['Origen'] == 'Oporto Costa', 'Camino'] = 'Costa'
clust_pred.loc[clust_pred['Origen'] == 'Oporto Costa', 'Camino'] = 'Costa'
clust_pred.loc[clust_pred['Origen'] == 'Oporto Costa', 'Etapa'] = 11

In [31]:
clust_pred[clust_pred.Etapa.isna()]

,Cluster,Origen,Camino,Latitud,Longitud,OrigenCamino,Etapa
Fecha,,,,,,,
2022-07-01 10:01:51,1.0,Cataluña,NaN,41.852309,1.574504,CataluñaOtros caminos,NaN
2022-07-01 09:11:23,NaN,Italia,NaN,42.638426,12.674297,ItaliaFrances,NaN
2022-07-01 09:02:12,2.0,Le Puy,NaN,44.661944,0.073889,Le PuyFrances,NaN
2022-07-01 09:13:00,2.0,Le Puy,NaN,44.661944,0.073889,Le PuyFrances,NaN
2022-07-01 09:18:56,2.0,Jaca,NaN,42.569252,-0.549372,JacaFrances,NaN
...,...,...,...,...,...,...,...
2022-07-11 19:01:39,1.0,Bayonne,NaN,43.494514,-1.473666,BayonneNorte,NaN
2022-07-11 19:01:43,1.0,Bayonne,NaN,43.494514,-1.473666,BayonneNorte,NaN
2022-07-11 19:03:07,1.0,Baiona,NaN,43.494514,-1.473666,BaionaCosta,NaN
2022-07-11 19:04:23,1.0,Baiona,NaN,43.494514,-1.473666,BaionaCosta,NaN
2022-07-11 19:04:43,1.0,Baiona,NaN,43.494514,-1.473666,BaionaCosta,NaN

In [32]:
def add_time_features(df):
    df = df.copy()
  
    df['dayofyear'] = df.index.dayofyear

    return df

In [33]:
pere_pas = add_time_features(clust_pred)

In [34]:
pere_pas.reset_index(inplace=True)

In [36]:
pere_pas.Etapa.mean()

9.897386304234187

In [102]:

df_itinerario =pd.DataFrame()

df_itinerario['Peregrino'] = pere_pas.index

df_itinerario

       Peregrino
0              0
1              1
2              2
3              3
4              4
...          ...
23627      23627
23628      23628
23629      23629
23630      23630
23631      23631

[23632 rows x 1 columns]

In [103]:
nombres_caminos = etaps.Camino.unique().tolist()

In [104]:
nombres_caminos

['Frances', 'Ingles', 'Norte', 'Portugues', 'Costa', 'Primitivo', 'Sanabrés']

In [105]:
lista_nombres =[]
for caminos in nombres_caminos:
    lista_nombres.append(caminos)

In [106]:
for l,caminos in zip(lista_nombres,nombres_caminos):
    aux =etaps[ etaps['Camino']== caminos]
    locals()[l] = aux['Origen']

In [107]:
Sanabres= Sanabrés

In [108]:
Sanabres

131    Santiago de Compostela
132                   Outeiro
133                    A Laxe
134                       Cea
135                   Ourense
136        Xunqueira de Ambía
137                      Laza
138                  A Gudiña
139                    Lubián
140        Puebla de Sanabria
141                   Mombuey
142       Santa Marta de Tera
143                    Tábara
144       Granja de Moreruela
Name: Origen, dtype: object

In [110]:
peregrinos_ = pere_pas[pere_pas.Etapa.notna()]
peregrinos_

,Fecha,Cluster,Origen,Camino,Latitud,Longitud,OrigenCamino,Etapa,dayofyear
0,2022-07-01 10:08:59,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182
1,2022-07-01 10:09:02,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182
2,2022-07-01 10:09:04,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182
3,2022-07-01 10:09:06,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182
4,2022-07-01 10:20:35,2.0,Sarria,Frances,42.778420,-7.414661,SarriaFrances,5.0,182
...,...,...,...,...,...,...,...,...,...
23621,2022-07-11 18:54:36,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192
23622,2022-07-11 18:54:41,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192
23623,2022-07-11 18:55:35,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192
23624,2022-07-11 18:56:01,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192
23625,2022-07-11 18:57:54,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192

In [112]:
peregrinos_.Etapa.max()

34.0

In [113]:
182-34

148

In [114]:
peregrinos_['llegada'] = peregrinos_.dayofyear - 148

/var/folders/rv/z0yvw1vn57j7rg7v3j11b_3r0000gn/T/ipykernel_32162/3255510226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  peregrinos_['llegada'] = peregrinos_.dayofyear - 148

In [115]:

df_itinerario =pd.DataFrame()

df_itinerario['Peregrino'] = peregrinos_.index

In [116]:
df_itinerario

       Peregrino
0              0
1              1
2              2
3              3
4              4
...          ...
19125      23621
19126      23622
19127      23623
19128      23624
19129      23625

[19130 rows x 1 columns]

In [118]:
peregrinos_

,Fecha,Cluster,Origen,Camino,Latitud,Longitud,OrigenCamino,Etapa,dayofyear,llegada
0,2022-07-01 10:08:59,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
1,2022-07-01 10:09:02,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
2,2022-07-01 10:09:04,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
3,2022-07-01 10:09:06,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
4,2022-07-01 10:20:35,2.0,Sarria,Frances,42.778420,-7.414661,SarriaFrances,5.0,182,34
...,...,...,...,...,...,...,...,...,...,...
23621,2022-07-11 18:54:36,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23622,2022-07-11 18:54:41,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23623,2022-07-11 18:55:35,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192,44
23624,2022-07-11 18:56:01,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23625,2022-07-11 18:57:54,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192,44

In [123]:
peregrinos_.Etapa.day()

array([11.,  5., 33.,  6., 13.,  7., 21.,  8., 14., 34., 30., 15., 32.,
        4.,  9., 27., 25., 22., 18., 26., 20., 10., 31., 23., 17., 28.,
       29.,  3., 24., 12., 19.])

In [126]:
Costa

102    Santiago de Compostela
103                    Padrón
104            Caldas de Reis
105                Pontevedra
106                 Redondela
107                      Vigo
108                 Ramallosa
109                    Mougás
110                   Caminha
111          Viana do Castelo
112                  Marinhas
113           Póvoa de Varzim
114                   Labruge
115                    Oporto
Name: Origen, dtype: object

In [124]:
for i in range(len(peregrinos_)):
    
    llegada = peregrinos_.iloc[i,8]
    etapa = peregrinos_.iloc[i,7]
    etapa = int(etapa)
    
    for e in range(etapa):
        camino = peregrinos_.iloc[i,3]
        if (camino =='Portugues por la costa'):
            camino = 'Costa'
        df_itinerario.loc[i,str(llegada)] = Frances.iloc[0]


        if e+1< len(locals()[camino]):
            df_itinerario.loc[i,str(llegada-e)] = locals()[camino].iloc[e+1]

In [125]:
df_itinerario

,Peregrino,182,181,180,179,178,177,176,175,174,...,183,184,185,186,187,188,189,190,191,192
0,0,Santiago de Compostela,Caldas de Reis,Pontevedra,Redondela,Vigo,Ramallosa,Mougás,Caminha,Viana do Castelo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Santiago de Compostela,Caldas de Reis,Pontevedra,Redondela,Vigo,Ramallosa,Mougás,Caminha,Viana do Castelo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Santiago de Compostela,Caldas de Reis,Pontevedra,Redondela,Vigo,Ramallosa,Mougás,Caminha,Viana do Castelo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Santiago de Compostela,Caldas de Reis,Pontevedra,Redondela,Vigo,Ramallosa,Mougás,Caminha,Viana do Castelo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Santiago de Compostela,Arzúa,Palas de Rei,Portomarín,Sarria,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19125,23621,Póvoa de Varzim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
19126,23622,Póvoa de Varzim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
19127,23623,Oporto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Vilarinho,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
19128,23624,Póvoa de Varzim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
19129,23625,Oporto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Vilarinho,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela

In [127]:
df_itinerario_sorted = df_itinerario.reindex(sorted(df_itinerario.columns), axis=1)

In [128]:
df_itinerario_sorted

,149,150,151,152,153,154,155,156,157,158,...,184,185,186,187,188,189,190,191,192,Peregrino
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela,23621
19126,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela,23622
19127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela,23623
19128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela,23624
19129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela,23625

In [129]:
df_itinerario_sorted.set_index('Peregrino', inplace=True)

In [130]:

# Obtener el índice de las columnas que representan días del año
dias_del_anio = [int(col) for col in df_itinerario_sorted.columns[1:]]


# Convertir los números en objetos de fecha y aplicar el formato deseado
nombres_columnas_nuevos = [pd.to_datetime('2022-12-31') + pd.DateOffset(days=dia) for dia in dias_del_anio]
nombres_columnas_nuevos = [fecha.strftime('%d/%m/%Y') for fecha in nombres_columnas_nuevos]

# Asignar los nuevos nombres de columna al DataFrame
df_itinerario_sorted.columns = df_itinerario_sorted.columns[:1].tolist() + nombres_columnas_nuevos

print(df_itinerario_sorted)

           149 30/05/2023 31/05/2023 01/06/2023 02/06/2023 03/06/2023  \
Peregrino
0          NaN        NaN        NaN        NaN        NaN        NaN
1          NaN        NaN        NaN        NaN        NaN        NaN
2          NaN        NaN        NaN        NaN        NaN        NaN
3          NaN        NaN        NaN        NaN        NaN        NaN
4          NaN        NaN        NaN        NaN        NaN        NaN
...        ...        ...        ...        ...        ...        ...
23621      NaN        NaN        NaN        NaN        NaN        NaN
23622      NaN        NaN        NaN        NaN        NaN        NaN
23623      NaN        NaN        NaN        NaN        NaN        NaN
23624      NaN        NaN        NaN        NaN        NaN        NaN
23625      NaN        NaN        NaN        NaN        NaN        NaN

          04/06/2023 05/06/2023 06/06/2023 07/06/2023  ... 02/07/2023  \
Peregrino                                              ...
0                NaN        NaN        NaN        NaN  ...        NaN
1                NaN        NaN        NaN        NaN  ...        NaN
2                NaN        NaN        NaN        NaN  ...        NaN
3                NaN        NaN        NaN        NaN  ...        NaN
4                NaN        NaN        NaN        NaN  ...        NaN
...              ...        ...        ...        ...  ...        ...
23621            NaN        NaN        NaN        NaN  ...   Marinhas
23622            NaN        NaN        NaN        NaN  ...   Marinhas
23623            NaN        NaN        NaN        NaN  ...  Vilarinho
23624            NaN        NaN        NaN        NaN  ...   Marinhas
23625            NaN        NaN        NaN        NaN  ...  Vilarinho

                 03/07/2023     04/07/2023 05/07/2023        06/07/2023  \
Peregrino
0                       NaN            NaN        NaN               NaN
1                       NaN            NaN        NaN               NaN
2                       NaN            NaN        NaN               NaN
3                       NaN            NaN        NaN               NaN
4                       NaN            NaN        NaN               NaN
...                     ...            ...        ...               ...
23621      Viana do Castelo        Caminha     Mougás         Ramallosa
23622      Viana do Castelo        Caminha     Mougás         Ramallosa
23623              Barcelos  Ponte de Lima    Rubiães  Valença do Minho
23624      Viana do Castelo        Caminha     Mougás         Ramallosa
23625              Barcelos  Ponte de Lima    Rubiães  Valença do Minho

          07/07/2023 08/07/2023  09/07/2023      10/07/2023  \
Peregrino
0                NaN        NaN         NaN             NaN
1                NaN        NaN         NaN             NaN
2                NaN        NaN         NaN             NaN
3                NaN        NaN         NaN             NaN
4                NaN        NaN         NaN             NaN
...              ...        ...         ...             ...
23621           Vigo  Redondela  Pontevedra  Caldas de Reis
23622           Vigo  Redondela  Pontevedra  Caldas de Reis
23623      O Porriño  Redondela  Pontevedra  Caldas de Reis
23624           Vigo  Redondela  Pontevedra  Caldas de Reis
23625      O Porriño  Redondela  Pontevedra  Caldas de Reis

                       11/07/2023
Peregrino
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
...                           ...
23621      Santiago de Compostela
23622      Santiago de Compostela
23623      Santiago de Compostela
23624      Santiago de Compostela
23625      Santiago de Compostela

[19130 rows x 44 columns]

In [131]:
df_itinerario_sorted

,149,30/05/2023,31/05/2023,01/06/2023,02/06/2023,03/06/2023,04/06/2023,05/06/2023,06/06/2023,07/06/2023,...,02/07/2023,03/07/2023,04/07/2023,05/07/2023,06/07/2023,07/07/2023,08/07/2023,09/07/2023,10/07/2023,11/07/2023
Peregrino,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23621,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
23622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
23623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Vilarinho,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
23624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Marinhas,Viana do Castelo,Caminha,Mougás,Ramallosa,Vigo,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela
23625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Vilarinho,Barcelos,Ponte de Lima,Rubiães,Valença do Minho,O Porriño,Redondela,Pontevedra,Caldas de Reis,Santiago de Compostela

In [133]:
peregrinos_

,Fecha,Cluster,Origen,Camino,Latitud,Longitud,OrigenCamino,Etapa,dayofyear,llegada
0,2022-07-01 10:08:59,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
1,2022-07-01 10:09:02,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
2,2022-07-01 10:09:04,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
3,2022-07-01 10:09:06,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,182,34
4,2022-07-01 10:20:35,2.0,Sarria,Frances,42.778420,-7.414661,SarriaFrances,5.0,182,34
...,...,...,...,...,...,...,...,...,...,...
23621,2022-07-11 18:54:36,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23622,2022-07-11 18:54:41,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23623,2022-07-11 18:55:35,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192,44
23624,2022-07-11 18:56:01,1.0,Oporto Costa,Costa,41.163505,-8.527522,Oporto CostaCosta,11.0,192,44
23625,2022-07-11 18:57:54,1.0,Oporto,Portugues,41.149451,-8.610788,OportoPortugues,11.0,192,44

In [134]:
codigo_cluster_dict = dict(zip( peregrinos_.index, peregrinos_['Cluster']))
codigo_cluster_dict

{0: 1.0,
 1: 1.0,
 2: 1.0,
 3: 1.0,
 4: 2.0,
 5: 2.0,
 6: 2.0,
 7: 2.0,
 8: 2.0,
 9: 2.0,
 10: 2.0,
 11: 2.0,
 12: 2.0,
 13: 2.0,
 14: 2.0,
 15: 2.0,
 16: 2.0,
 17: 2.0,
 18: 2.0,
 19: 2.0,
 20: 2.0,
 21: 2.0,
 22: 2.0,
 23: 2.0,
 24: 2.0,
 25: 1.0,
 26: 1.0,
 27: 2.0,
 28: 2.0,
 29: 2.0,
 30: 2.0,
 31: nan,
 32: 2.0,
 33: 2.0,
 34: 2.0,
 35: 2.0,
 36: nan,
 37: 2.0,
 38: 1.0,
 39: 1.0,
 41: 1.0,
 43: 2.0,
 44: 2.0,
 46: 1.0,
 48: 1.0,
 49: 0.0,
 50: 2.0,
 51: 1.0,
 52: 1.0,
 53: 2.0,
 54: 2.0,
 55: 2.0,
 56: 2.0,
 57: 2.0,
 58: 2.0,
 59: 2.0,
 60: 1.0,
 61: 2.0,
 62: 2.0,
 63: nan,
 64: 1.0,
 65: 2.0,
 66: 1.0,
 67: 2.0,
 68: 2.0,
 69: 2.0,
 70: 2.0,
 71: 2.0,
 72: 2.0,
 73: 2.0,
 74: 2.0,
 75: 2.0,
 76: 2.0,
 77: 2.0,
 78: 2.0,
 79: 2.0,
 80: 2.0,
 81: 2.0,
 82: 0.0,
 83: 1.0,
 84: 2.0,
 85: 2.0,
 86: 2.0,
 87: 2.0,
 88: 2.0,
 89: 2.0,
 90: 2.0,
 91: 0.0,
 92: 1.0,
 93: 1.0,
 94: 2.0,
 95: 2.0,
 96: 2.0,
 97: 1.0,
 98: 1.0,
 99: 2.0,
 100: 1.0,
 101: 2.0,
 102: 2.0,
 103: 2.0,
 104: 1.0,
 105: nan,
 107: 0.0,
 108: 1.0,
 110: 2.0,
 111: 2.0,
 112: 2.0,
 113: 2.0,
 114: 2.0,
 116: 2.0,
 117: 2.0,
 118: 1.0,
 119: 2.0,
 120: 2.0,
 121: 1.0,
 122: 1.0,
 123: 0.0,
 125: 2.0,
 127: 1.0,
 128: 1.0,
 130: 1.0,
 131: 1.0,
 132: 0.0,
 133: 1.0,
 134: 1.0,
 135: 2.0,
 136: 2.0,
 137: 2.0,
 139: 2.0,
 140: 2.0,
 141: 2.0,
 142: 2.0,
 143: 2.0,
 144: nan,
 145: 1.0,
 146: nan,
 148: 2.0,
 150: 2.0,
 151: 1.0,
 152: 0.0,
 153: 1.0,
 154: 1.0,
 155: 1.0,
 156: 1.0,
 157: 2.0,
 158: 2.0,
 159: 2.0,
 160: 1.0,
 161: 2.0,
 162: 1.0,
 163: 1.0,
 164: 2.0,
 165: 2.0,
 166: 1.0,
 167: 1.0,
 168: 2.0,
 170: 1.0,
 171: 2.0,
 172: 1.0,
 173: 1.0,
 174: 1.0,
 175: 2.0,
 177: 1.0,
 178: 1.0,
 179: 2.0,
 180: 2.0,
 181: 0.0,
 182: 2.0,
 183: 1.0,
 184: 2.0,
 185: 1.0,
 186: 2.0,
 187: 1.0,
 188: 2.0,
 189: 2.0,
 190: 1.0,
 191: 1.0,
 192: 1.0,
 193: 1.0,
 194: 2.0,
 195: 1.0,
 196: 2.0,
 197: nan,
 198: 1.0,
 199: nan,
 200: 2.0,
 201: 1.0,
 202: 2.0,
 203: 2.0,
 204: nan,
 206: 2.0,
 207: 1.0,
 208: 2.0,
 209: nan,
 210: 1.0,
 211: 2.0,
 212: 2.0,
 213: nan,
 214: 2.0,
 215: 0.0,
 216: 2.0,
 217: 1.0,
 218: 2.0,
 220: 1.0,
 221: 2.0,
 222: 1.0,
 223: 2.0,
 225: 1.0,
 226: 2.0,
 227: 2.0,
 228: 1.0,
 229: 1.0,
 230: 0.0,
 232: 1.0,
 233: 1.0,
 234: 2.0,
 237: 1.0,
 238: 1.0,
 239: 1.0,
 241: 0.0,
 242: 2.0,
 243: 1.0,
 244: 0.0,
 245: 1.0,
 247: 1.0,
 248: 2.0,
 249: 2.0,
 250: 2.0,
 251: 2.0,
 252: 2.0,
 253: 1.0,
 254: 2.0,
 255: 2.0,
 256: 2.0,
 257: 1.0,
 258: 1.0,
 259: 1.0,
 260: 1.0,
 261: 1.0,
 262: 1.0,
 263: 1.0,
 264: 0.0,
 265: 1.0,
 266: 1.0,
 267: 1.0,
 268: 1.0,
 269: 1.0,
 271: 1.0,
 273: 1.0,
 274: 1.0,
 275: 1.0,
 276: 1.0,
 277: 2.0,
 279: 2.0,
 280: 1.0,
 281: 1.0,
 282: 0.0,
 283: 1.0,
 285: 2.0,
 287: 1.0,
 288: 2.0,
 289: 2.0,
 290: 2.0,
 291: 2.0,
 292: 1.0,
 293: 2.0,
 294: 2.0,
 295: 2.0,
 296: 2.0,
 297: 2.0,
 298: 2.0,
 299: 1.0,
 300: 2.0,
 301: 2.0,
 302: 2.0,
 303: 2.0,
 304: 0.0,
 305: 2.0,
 307: 1.0,
 308: 1.0,
 310: 2.0,
 311: 1.0,
 312: 2.0,
 313: 1.0,
 315: 2.0,
 317: 2.0,
 318: 2.0,
 319: 2.0,
 321: 2.0,
 322: 1.0,
 323: 1.0,
 324: 1.0,
 325: 2.0,
 326: 2.0,
 327: 2.0,
 328: 2.0,
 329: 2.0,
 330: 2.0,
 331: 2.0,
 332: 2.0,
 333: 2.0,
 334: 2.0,
 335: 2.0,
 336: 2.0,
 337: 2.0,
 338: 2.0,
 339: 2.0,
 340: 1.0,
 341: 2.0,
 342: 2.0,
 343: 2.0,
 344: 2.0,
 345: 2.0,
 346: 2.0,
 347: 2.0,
 348: 2.0,
 349: 2.0,
 351: 2.0,
 352: 2.0,
 353: 2.0,
 354: 2.0,
 355: 1.0,
 356: 2.0,
 357: 2.0,
 358: 2.0,
 359: 2.0,
 360: 1.0,
 361: 2.0,
 362: 2.0,
 363: 2.0,
 364: 2.0,
 365: 2.0,
 366: 2.0,
 367: 2.0,
 368: 2.0,
 369: 2.0,
 370: 2.0,
 371: 2.0,
 372: 2.0,
 373: 2.0,
 374: 2.0,
 375: 2.0,
 376: 2.0,
 377: 2.0,
 378: 2.0,
 379: 2.0,
 380: 2.0,
 381: 2.0,
 382: 2.0,
 383: 1.0,
 384: 1.0,
 385: 1.0,
 386: 1.0,
 387: 1.0,
 388: 1.0,
 389: 2.0,
 390: 1.0,
 391: 2.0,
 392: 2.0,
 393: 2.0,
 394: 2.0,
 395: 2.0,
 396: 2.0,
 397: 2.0,
 398: 2.0,
 399: 2.0,
 400: 2.0,
 401: 2.0,
 402: 1.0,
 403: nan,
 404: 1.0,
 405: 1.0,
 407: 1.0,
 408: 2.0,
 409: 1.0,
 410: 2.0,
 411: 2.0,
 412: 2.0,
 413: 2.0,
 414: 2.0,
 415: 2.0,
 416: 2.0,
 417: 2.0,
 418: 2.0,
 419: 2.0,
 420: 1.0,
 421: 0.0,
 422: 0.0,
 423: nan,
 424: 2.0,
 425: 2.0,
 426: 2.0,
 428: 1.0,
 429: 1.0,
 430: 2.0,
 431: 2.0,
 432: 2.0,
 433: 2.0,
 434: 2.0,
 435: 2.0,
 436: 2.0,
 437: 2.0,
 438: 2.0,
 439: 2.0,
 440: 2.0,
 441: 2.0,
 442: 2.0,
 443: 2.0,
 444: 2.0,
 445: 2.0,
 447: 1.0,
 448: 1.0,
 449: 1.0,
 451: 2.0,
 452: 2.0,
 453: 1.0,
 454: 1.0,
 466: 2.0,
 467: 2.0,
 468: 2.0,
 469: 2.0,
 470: 2.0,
 471: 0.0,
 472: 0.0,
 473: 0.0,
 474: 0.0,
 475: 0.0,
 476: 0.0,
 477: 0.0,
 478: 0.0,
 479: 0.0,
 480: 0.0,
 481: 0.0,
 482: 0.0,
 483: 0.0,
 484: 0.0,
 485: 0.0,
 486: 2.0,
 487: 2.0,
 488: 2.0,
 489: 2.0,
 490: 2.0,
 496: 1.0,
 497: 2.0,
 498: 2.0,
 499: 2.0,
 500: 2.0,
 501: 2.0,
 502: 2.0,
 503: 2.0,
 504: 1.0,
 505: 2.0,
 506: 2.0,
 507: 2.0,
 508: 2.0,
 509: 2.0,
 510: 2.0,
 511: 2.0,
 512: 1.0,
 513: 2.0,
 514: 2.0,
 515: 1.0,
 517: 1.0,
 520: 1.0,
 521: 1.0,
 522: 1.0,
 523: 1.0,
 524: 1.0,
 525: 1.0,
 526: 2.0,
 527: 2.0,
 528: 2.0,
 529: 1.0,
 530: 0.0,
 534: nan,
 535: 2.0,
 536: 1.0,
 537: 1.0,
 538: 2.0,
 540: 2.0,
 541: 1.0,
 542: 2.0,
 543: nan,
 545: 2.0,
 546: 0.0,
 547: 0.0,
 548: 0.0,
 549: 0.0,
 550: 0.0,
 551: 0.0,
 552: 0.0,
 553: 0.0,
 554: 0.0,
 555: 0.0,
 557: 0.0,
 558: 0.0,
 559: 0.0,
 560: 0.0,
 561: 0.0,
 562: 0.0,
 563: 0.0,
 564: 0.0,
 565: 0.0,
 566: 1.0,
 567: 1.0,
 568: 1.0,
 569: 1.0,
 570: 1.0,
 571: 1.0,
 572: 1.0,
 573: 1.0,
 574: 1.0,
 575: 1.0,
 577: 2.0,
 578: 2.0,
 579: 1.0,
 584: 1.0,
 586: 2.0,
 587: 2.0,
 588: 2.0,
 589: 2.0,
 590: 2.0,
 591: nan,
 592: 2.0,
 593: 1.0,
 594: 1.0,
 595: 2.0,
 596: 2.0,
 597: 2.0,
 598: 2.0,
 599: 2.0,
 600: 2.0,
 601: 1.0,
 602: 1.0,
 606: 2.0,
 607: 2.0,
 608: 1.0,
 609: 2.0,
 610: nan,
 611: 2.0,
 627: 0.0,
 628: 0.0,
 629: 0.0,
 630: 0.0,
 631: 0.0,
 632: 2.0,
 633: 0.0,
 634: 0.0,
 635: 2.0,
 636: 0.0,
 637: 0.0,
 638: 0.0,
 639: 0.0,
 640: 0.0,
 641: 0.0,
 642: 0.0,
 643: 0.0,
 644: 0.0,
 645: 0.0,
 646: 0.0,
 688: 2.0,
 690: 1.0,
 691: 1.0,
 692: 2.0,
 693: 0.0,
 694: 1.0,
 695: 2.0,
 696: 1.0,
 697: 1.0,
 698: 1.0,
 699: 2.0,
 700: 2.0,
 701: 2.0,
 702: 1.0,
 703: 2.0,
 704: 2.0,
 705: 2.0,
 706: 1.0,
 707: 1.0,
 708: 1.0,
 709: 1.0,
 710: 1.0,
 711: 1.0,
 712: 1.0,
 713: 1.0,
 714: 1.0,
 715: 1.0,
 716: 1.0,
 717: 1.0,
 718: 0.0,
 719: 2.0,
 720: 2.0,
 721: 2.0,
 722: 2.0,
 723: 2.0,
 724: nan,
 725: 1.0,
 726: 1.0,
 727: 1.0,
 728: 2.0,
 729: 1.0,
 730: 1.0,
 731: 2.0,
 734: 1.0,
 735: 1.0,
 736: 2.0,
 737: 2.0,
 738: 2.0,
 739: 0.0,
 740: 1.0,
 741: 2.0,
 742: 2.0,
 743: 1.0,
 744: 2.0,
 745: 0.0,
 746: 1.0,
 747: 1.0,
 748: 0.0,
 749: 1.0,
 750: 2.0,
 752: 1.0,
 753: 1.0,
 759: 1.0,
 760: 1.0,
 761: 1.0,
 762: 2.0,
 763: 1.0,
 765: 2.0,
 768: 2.0,
 769: 2.0,
 770: 0.0,
 771: 2.0,
 772: 2.0,
 773: 2.0,
 774: 0.0,
 777: nan,
 778: 2.0,
 779: 1.0,
 780: 1.0,
 781: 1.0,
 782: 1.0,
 783: 1.0,
 784: 1.0,
 785: 2.0,
 786: 0.0,
 787: 1.0,
 788: 1.0,
 789: 1.0,
 790: 1.0,
 791: nan,
 792: nan,
 793: 0.0,
 794: nan,
 795: 1.0,
 796: 1.0,
 797: 1.0,
 798: 1.0,
 799: 1.0,
 800: 2.0,
 801: 1.0,
 802: 1.0,
 803: 1.0,
 804: 2.0,
 805: 2.0,
 806: 2.0,
 807: 1.0,
 808: 1.0,
 809: 1.0,
 810: 2.0,
 811: 1.0,
 812: 1.0,
 813: nan,
 814: 2.0,
 815: 2.0,
 816: 2.0,
 817: 2.0,
 818: 1.0,
 819: 1.0,
 820: 1.0,
 821: 1.0,
 822: 1.0,
 823: 1.0,
 824: 1.0,
 825: 1.0,
 826: 1.0,
 827: 1.0,
 828: 1.0,
 829: 1.0,
 830: 2.0,
 831: 1.0,
 832: 1.0,
 833: 2.0,
 834: 2.0,
 835: 1.0,
 836: 2.0,
 837: 1.0,
 838: 1.0,
 839: 1.0,
 840: 1.0,
 841: 1.0,
 842: 1.0,
 843: 1.0,
 844: 1.0,
 845: 1.0,
 846: 1.0,
 847: 1.0,
 848: 1.0,
 849: 1.0,
 850: 2.0,
 851: 1.0,
 852: 1.0,
 853: 1.0,
 854: 1.0,
 855: 1.0,
 856: 1.0,
 857: 1.0,
 858: 1.0,
 859: 0.0,
 860: 1.0,
 861: 1.0,
 862: 1.0,
 863: 1.0,
 864: 1.0,
 865: 1.0,
 866: 1.0,
 867: nan,
 868: 0.0,
 869: 1.0,
 870: 1.0,
 871: 2.0,
 872: 1.0,
 873: 1.0,
 874: 1.0,
 875: 1.0,
 876: 1.0,
 877: 1.0,
 878: 1.0,
 879: 1.0,
 880: 1.0,
 881: 1.0,
 882: 1.0,
 883: 1.0,
 884: 1.0,
 885: 1.0,
 886: 1.0,
 887: 2.0,
 888: 1.0,
 889: 1.0,
 890: 1.0,
 891: 1.0,
 892: 1.0,
 893: 1.0,
 894: 1.0,
 895: 1.0,
 896: 1.0,
 897: 1.0,
 898: 1.0,
 899: 1.0,
 900: 1.0,
 901: 1.0,
 902: 1.0,
 903: 1.0,
 904: 1.0,
 905: 1.0,
 906: 1.0,
 907: 2.0,
 909: 2.0,
 913: 2.0,
 916: 2.0,
 917: 1.0,
 918: 1.0,
 919: 1.0,
 920: 1.0,
 921: 1.0,
 922: 1.0,
 923: 1.0,
 924: 1.0,
 925: nan,
 926: 1.0,
 927: 1.0,
 928: 0.0,
 929: 1.0,
 930: 1.0,
 931: 1.0,
 932: 1.0,
 933: 1.0,
 934: 1.0,
 935: 1.0,
 936: 1.0,
 937: 1.0,
 938: 1.0,
 939: 1.0,
 940: 1.0,
 941: 1.0,
 942: 1.0,
 943: 1.0,
 944: 2.0,
 945: 1.0,
 946: 2.0,
 947: 2.0,
 948: 2.0,
 949: 0.0,
 950: 1.0,
 951: 1.0,
 952: 1.0,
 953: 1.0,
 954: 1.0,
 955: 1.0,
 956: 1.0,
 957: 2.0,
 959: 2.0,
 960: 1.0,
 961: nan,
 962: 0.0,
 963: 2.0,
 964: nan,
 965: nan,
 967: 2.0,
 968: 2.0,
 969: 2.0,
 970: 2.0,
 972: 1.0,
 973: 2.0,
 974: 2.0,
 975: 2.0,
 976: 1.0,
 977: nan,
 978: 2.0,
 979: 2.0,
 980: 2.0,
 981: 2.0,
 982: 2.0,
 983: 2.0,
 984: 2.0,
 985: 2.0,
 986: 2.0,
 987: 2.0,
 988: 2.0,
 989: 2.0,
 990: 2.0,
 991: 2.0,
 992: 2.0,
 993: 2.0,
 994: 2.0,
 996: 1.0,
 997: 2.0,
 998: 2.0,
 999: 1.0,
 1000: 0.0,
 1001: 2.0,
 1002: 2.0,
 1003: 2.0,
 1004: 2.0,
 1005: 2.0,
 1006: 1.0,
 1007: 2.0,
 1008: nan,
 1010: 1.0,
 1011: 1.0,
 1013: 1.0,
 1014: 2.0,
 1015: 2.0,
 1016: 2.0,
 1017: 1.0,
 1018: 2.0,
 1019: 2.0,
 1020: 2.0,
 1021: 2.0,
 1022: 1.0,
 1023: 1.0,
 1024: 1.0,
 1025: 2.0,
 1026: 2.0,
 1027: 2.0,
 1028: 2.0,
 1029: 2.0,
 1030: 2.0,
 1031: 2.0,
 1032: 2.0,
 1033: 2.0,
 1034: 2.0,
 1035: 2.0,
 1036: 2.0,
 1037: 2.0,
 1038: 2.0,
 1039: 2.0,
 1040: 2.0,
 1041: 2.0,
 1042: 2.0,
 1043: 2.0,
 1044: 2.0,
 1045: 2.0,
 1046: 2.0,
 1047: 2.0,
 1048: 2.0,
 1049: 2.0,
 1050: 2.0,
 1051: 2.0,
 1052: 2.0,
 1053: 2.0,
 1054: 2.0,
 1055: 2.0,
 1056: 2.0,
 1057: 2.0,
 1058: 2.0,
 1059: 2.0,
 1060: 2.0,
 1061: 2.0,
 1062: 2.0,
 1063: 2.0,
 1064: 2.0,
 1065: 2.0,
 1066: 2.0,
 1067: 2.0,
 1068: 2.0,
 1069: 2.0,
 1070: 2.0,
 1071: 0.0,
 1072: 1.0,
 1073: 1.0,
 1074: 1.0,
 1075: 1.0,
 1076: 2.0,
 1077: 2.0,
 1078: 2.0,
 1079: 2.0,
 1080: 2.0,
 1081: 1.0,
 1082: 1.0,
 1083: 1.0,
 1084: 1.0,
 1085: 2.0,
 1086: 2.0,
 1087: 2.0,
 1088: 2.0,
 1089: 2.0,
 1090: 1.0,
 1091: 2.0,
 1092: 2.0,
 1093: 2.0,
 1094: 2.0,
 1095: nan,
 1096: 1.0,
 1097: 2.0,
 1098: 2.0,
 1099: 2.0,
 1100: 2.0,
 1101: 2.0,
 1102: 2.0,
 1103: 1.0,
 1104: 2.0,
 1105: 2.0,
 1106: 2.0,
 1107: 2.0,
 1108: 2.0,
 1109: nan,
 1110: 2.0,
 1111: 2.0,
 1112: 0.0,
 1113: 1.0,
 1114: 2.0,
 1115: 2.0,
 1116: 2.0,
 1117: 2.0,
 1118: 1.0,
 1119: 2.0,
 1120: 2.0,
 1121: 2.0,
 1122: 2.0,
 1123: 1.0,
 1124: 2.0,
 1125: 2.0,
 1126: 1.0,
 1127: 1.0,
 1128: 1.0,
 1129: 1.0,
 1130: 2.0,
 1131: 2.0,
 1132: 1.0,
 1133: 2.0,
 1134: 0.0,
 1135: 1.0,
 1136: nan,
 1137: nan,
 1138: 2.0,
 1140: 2.0,
 1141: nan,
 1142: nan,
 1143: 1.0,
 1144: 2.0,
 1145: 1.0,
 1146: nan,
 1147: 1.0,
 1148: 2.0,
 1149: 2.0,
 1150: 2.0,
 1151: 2.0,
 1152: 2.0,
 1153: 2.0,
 1154: 2.0,
 ...}