In [1]:
import pandas as pd

In [3]:
clust = pd.read_csv('Treated_csv/entries_with_labels_fin.csv')
clust = clust.set_index('Fecha')
clust.index = pd.to_datetime(clust.index)

In [5]:
clust[clust.Año == 2022]

,Sexo,Edad,Continente,Pais,Autonomia,Medio,Motivo,Camino,Origen,Profesion,Latitud,Longitud,Año,Mes,Dia,Dialv,Cluster
Fecha,,,,,,,,,,,,,,,,,
2022-06-17 18:58:36,M,49,Europa,Italia,NaN,Bicicleta,Religioso y otros,Frances-Camino de,Lourdes,Estudiantes,43.094090,-0.046497,2022,6,17,Friday,2.0
2022-01-01 10:00:29,M,56,Europa,España,Castilla León,Pie,Religioso,Frances-Camino de,Cebreiro,Empleados,42.889816,-8.309183,2022,1,1,Saturday,0.0
2022-01-01 10:00:29,F,11,Europa,España,Canarias,Caballo,Religioso,Costa Camino Portugues,Baiona,Estudiantes,43.494514,-1.473666,2022,1,1,Saturday,1.0
2022-01-01 10:27:56,F,44,Europa,España,Canarias,Pie,Religioso,Costa Camino Portugues,Baiona,Otros,43.494514,-1.473666,2022,1,1,Saturday,1.0
2022-01-01 10:00:29,M,75,Europa,España,Castilla León,Pie,Religioso y otros,Portugues-Camino,Oporto,Jubilados,41.149451,-8.610788,2022,1,1,Saturday,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 16:45:23,M,56,Europa,Portugal,Residentes Extranjero,Bicicleta,Religioso y otros,Portugues-Camino,Lisboa,Otros,38.707751,-9.136592,2022,12,31,Saturday,1.0
2022-12-31 16:45:23,M,55,Europa,Portugal,Residentes Extranjero,Bicicleta,Religioso y otros,Portugues-Camino,Lisboa,Otros,38.707751,-9.136592,2022,12,31,Saturday,1.0
2022-12-31 16:45:23,M,28,Europa,Portugal,Residentes Extranjero,Bicicleta,Religioso y otros,Portugues-Camino,Lisboa,Otros,38.707751,-9.136592,2022,12,31,Saturday,1.0
2022-12-31 16:45:23,M,16,Europa,Portugal,Residentes Extranjero,Bicicleta,Religioso y otros,Portugues-Camino,Lisboa,Otros,38.707751,-9.136592,2022,12,31,Saturday,1.0
2022-12-31 16:45:24,M,52,Europa,Portugal,Residentes Extranjero,Bicicleta,Religioso y otros,Portugues-Camino,Lisboa,Otros,38.707751,-9.136592,2022,12,31,Saturday,1.0

In [6]:
clust[clust.Año == 2019]

,Sexo,Edad,Continente,Pais,Autonomia,Medio,Motivo,Camino,Origen,Profesion,Latitud,Longitud,Año,Mes,Dia,Dialv,Cluster
Fecha,,,,,,,,,,,,,,,,,
2019-01-02 00:00:00,F,61,África,Sudáfrica,NaN,Pie,Religioso y otros,Portugues-Camino,Oporto,Profesores,41.149451,-8.610788,2019,1,2,Wednesday,NaN
2019-01-02 00:00:00,M,60,África,Sudáfrica,NaN,Pie,Religioso y otros,Portugues-Camino,Oporto,Tecnicos,41.149451,-8.610788,2019,1,2,Wednesday,NaN
2019-01-02 00:00:00,M,37,Europa,España,Comunidad Valenciana,Pie,Religioso,Frances-Camino de,Sarria,Tecnicos,42.778420,-7.414661,2019,1,2,Wednesday,0.0
2019-01-02 00:00:00,F,22,América del Sur,Uruguay,NaN,Pie,Religioso y otros,Ingles-Camino,Ferrol,Estudiantes,43.484686,-8.233162,2019,1,2,Wednesday,NaN
2019-01-02 00:00:00,F,56,América del Norte,Estados Unidos,NaN,Pie,Religioso y otros,Muxia-Finisterre,Finisterra,Funcionarios,48.245115,-4.044090,2019,1,2,Wednesday,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 08:42:05,M,20,Europa,Italia,NaN,Pie,Religioso y otros,Frances-Camino de,Sarria,Agricultores,42.778420,-7.414661,2019,12,31,Tuesday,0.0
2019-12-31 08:42:05,M,21,Asia,China,NaN,Pie,Religioso y otros,Frances-Camino de,Sarria,Estudiantes,42.778420,-7.414661,2019,12,31,Tuesday,NaN
2019-12-31 08:42:05,F,19,Asia,China,NaN,Pie,Religioso y otros,Frances-Camino de,Sarria,Estudiantes,42.778420,-7.414661,2019,12,31,Tuesday,NaN
2019-12-31 08:42:05,M,38,América del Norte,Estados Unidos,NaN,Pie,Religioso,Frances-Camino de,Ferreiros,Tecnicos,42.785838,-7.531606,2019,12,31,Tuesday,0.0
2019-12-31 08:42:05,F,37,América del Norte,Estados Unidos,NaN,Pie,Religioso,Frances-Camino de,Ferreiros,Profesores,42.785838,-7.531606,2019,12,31,Tuesday,0.0

In [7]:
50 * 9 * 350000

157500000

In [8]:
clust.Edad.mean()

42.19827208989122