In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../data/raw/2019.xlsx")

In [4]:
df18 = pd.read_excel("../data/raw/2018.xlsx")

In [5]:
df18

,Entrada,Fecha,Sexo,Edad,Continente,Pais,Autonomia,Medio,Motivo,Camino,Origen,Profesion
0,2018-01/0001-01,2018-01-02,M,36,Europa,España,Cataluña,Pie,Religioso y otros,Portugues-Camino,Oporto,Obreros
1,2018-01/0001-02,2018-01-02,M,28,Asia,Corea,NaN,Pie,Religioso y otros,Frances-Camino de,S. Jean P. Port,Estudiantes
2,2018-01/0001-03,2018-01-02,M,24,Asia,Corea,NaN,Pie,Religioso y otros,Frances-Camino de,S. Jean P. Port,Estudiantes
3,2018-01/0001-04,2018-01-02,M,54,Europa,España,Castilla León,Pie,Religioso,Frances-Camino de,Francia - C.F.,Parados
4,2018-01/0001-05,2018-01-02,F,29,Europa,España,Cataluña,Pie,No religioso,Frances-Camino de,Roncesvalles,Estudiantes
...,...,...,...,...,...,...,...,...,...,...,...,...
327362,2018-12/16494-16,2018-12-31,M,42,América del Sur,Venezuela,NaN,Pie,Religioso,Frances-Camino de,Sarria,Liberales
327363,2018-12/16494-17,2018-12-31,F,57,Europa,Portugal,NaN,Pie,Religioso,Ingles-Camino,A Coruña,Profesores
327364,2018-12/16494-18,2018-12-31,F,48,Europa,Portugal,NaN,Pie,Religioso y otros,Ingles-Camino,A Coruña,Profesores
327365,2018-12/16494-19,2018-12-31,F,31,Europa,Ucrania,NaN,Pie,Religioso,Via de la Plata,Ourense,Liberales
327366,2018-12/16494-20,2018-12-31,F,26,Europa,Ucrania,NaN,Pie,Religioso y otros,Invierno de Camino,Chantada,Estudiantes

In [3]:
df

,Entrada,Fecha,Sexo,Edad,Continente,Pais,Autonomia,Medio,Motivo,Camino,Origen,Profesion
0,2019-01/0002-01,2019-01-02 00:00:00,F,61,África,Sudáfrica,NaN,Pie,Religioso y otros,Portugues-Camino,Oporto,Profesores
1,2019-01/0002-02,2019-01-02 00:00:00,M,60,África,Sudáfrica,NaN,Pie,Religioso y otros,Portugues-Camino,Oporto,Tecnicos
2,2019-01/0002-03,2019-01-02 00:00:00,M,37,Europa,España,Comunidad Valenciana,Pie,Religioso,Frances-Camino de,Sarria,Tecnicos
3,2019-01/0002-04,2019-01-02 00:00:00,F,22,América del Sur,Uruguay,NaN,Pie,Religioso y otros,Ingles-Camino,Ferrol,Estudiantes
4,2019-01/0002-05,2019-01-02 00:00:00,F,56,América del Norte,Estados Unidos,NaN,Pie,Religioso y otros,Muxia-Finisterre,Finisterra,Funcionarios
...,...,...,...,...,...,...,...,...,...,...,...,...
347444,2019-12/19035-17,2019-12-31 08:42:05,M,21,Asia,China,NaN,Pie,Religioso y otros,Frances-Camino de,Sarria,Estudiantes
347445,2019-12/19035-18,2019-12-31 08:42:05,F,19,Asia,China,NaN,Pie,Religioso y otros,Frances-Camino de,Sarria,Estudiantes
347446,2019-12/19035-19,2019-12-31 08:42:05,M,38,América del Norte,Estados Unidos,NaN,Pie,Religioso,Frances-Camino de,Ferreiros,Tecnicos
347447,2019-12/19035-20,2019-12-31 08:42:05,F,37,América del Norte,Estados Unidos,NaN,Pie,Religioso,Frances-Camino de,Ferreiros,Profesores
347448,2019-01/0059-01,2019-01-20 14:13:29,M,48,Europa,España,Andalucía,Pie,Religioso y otros,Frances-Camino de,Astorga,Funcionarios